language: node_js
cache: npm

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^greenkeeper.*$/

jobs:
  include:
    - stage: test
      node_js: 8
      script: npm run test
    - node_js: 10
      env: Node 10 & coverage upload
      after_script:
        - npm run coverage:upload
    - node_js: lts/*
      env: memory-test
      script: npm run test:memory
    - node_js: lts/*
      env: build test
      script: npm run build
    - node_js: lts/*
      env: bundle size
      script:
        - npm run build
        - npx terser pkg/dist-web/index.bundled.js --output pkg/dist-web/index.bundled.min.js --compress --mangle
        - npx bundlesize --files pkg/dist-web/index.bundled.min.js --max-size 4KB

    # release stage: run semantic release & update the docs
    - stage: release
      env: semantic-release
      node_js: lts/*
      script:
        - npm run build
        - cd pkg && npx semantic-release

    # when Greenkeeper updates @octokit/routes, run "generate-routes" script
    # and push new routes.json file to the pull request
    - stage: greenkeeper-routes-update
      node_js: lts/*
      script:
        - git checkout $TRAVIS_BRANCH
        # generate triggers-notification-paths.js file (without proper formatting)
        - node scripts/generate-routes
        # run standard fix on that file to fix formatting
        - npx standard src/triggers-notification-paths.js --fix
        # commit changes and push back to branch on GitHub. If there are no changes then exit without error
        - 'git commit -a -m "build: routes" --author="Octokit Bot <octokitbot@martynus.net>" && git push "https://${GH_TOKEN}@github.com/$TRAVIS_REPO_SLUG" ${TRAVIS_BRANCH} || true'

stages:
  - test
  - name: release
    if: branch = master AND type IN (push)
  - name: greenkeeper-routes-update
    if: branch =~ ^greenkeeper/@octokit/routes
