name: Update
"on":
  repository_dispatch:
    types:
      - octokit/openapi release
  workflow_dispatch:
    inputs:
      version:
        description: Version of https://www.npmjs.com/package/@octokit/openapi
        required: true
jobs:
  update_routes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - uses: actions/setup-node@5b949b50c3461bbcd5a540b150c368278160234a # tag=v3
        with:
          cache: npm
          node-version: 16
      - run: git checkout routes-update || true
      - run: npm ci
      - run: rm -rf docs/
      - run: npm run update-endpoints
        if: github.event_name == 'repository_dispatch'
        env:
          VERSION: ${{ github.event.client_payload.release.tag_name }}
      - run: npm run update-endpoints
        if: github.event_name == 'workflow_dispatch'
        env:
          VERSION: ${{ github.event.inputs.version }}
      - name: Create Pull Request
        uses: gr2m/create-or-update-pull-request-action@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.OCTOKITBOT_PAT }}
        with:
          title: 🚧 GitHub OpenAPI specifications changed
          body: >
            Make sure to update the commits so that the merge results in helpful
            release notes, see [Merging the Pull Request & releasing a new
            version](https://github.com/octokit/rest.js/blob/master/CONTRIBUTING.md#merging-the-pull-request--releasing-a-new-version).


            In general


            - Avoid breaking changes at all costs

            - If there are no typescript or code changes, use a `docs` prefix

            - If there are typescript changes but no code changes, use
            `fix(typescript)` prefix

            - If there are code changes, use `fix` if a problem was resolved,
            `feat` if new endpoints / parameters were added, and
            `feat(deprecation)` if a method was deprecated.
          branch: openapi-update
          commit-message: WIP octokit/openapi updated
          author: Octokit Bot <33075676+octokitbot@users.noreply.github.com>
          labels: maintenance
